on: [push]

permissions:
  contents: write

name: CI

jobs:
  build_and_archive_musig_banano_wasm:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: prep toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
      - name: cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target wasm32-unknown-unknown --release
      - name: archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: musig_banano.wasm
          path: |
            target/wasm32-unknown-unknown/release/musig_banano.wasm
      - name: release wasm
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/wasm32-unknown-unknown/release/musig_banano.wasm
  build_test_and_archive_typescript_integration:
    name: typescript integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v17
        with:
          # Mostly to avoid GitHub rate limiting
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: build and test typescript integration
        run: nix develop --command bash -c "rustup default stable && make build && cd typescript_integration && npm install && npm run build && npm run awesometest"
      - name: Deploy mochawesome report page
        uses: peaceiris/actions-gh-pages@v3
        with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: typescript_integration/mochawesome-report
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com' 
      - name: archive typescript_extension_dist_directory
        uses: actions/upload-artifact@v3
        with:
          name: typescript_integration_dist_directory
          path: |
            typescript_integration/dist/
      - name: release dist dir
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: typescript_integration/dist/**
  
